name: lundri_connect

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.5+1
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  cached_network_image: ^3.4.1
  file_picker: ^11.0.2
  video_player: ^2.10.1
  firebase_storage: ^13.3.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.13.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  geoflutterfire_plus: ^0.0.34
  audioplayers: ^6.6.0
  package_info_plus: ^9.0.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/lundri_connect_logo.png"

flutter_native_splash:
  color: "#FF6B4A"
  # image: assets/icons/lundri_connect_logo.png

  android_12:
    color: "#FF6B4A"
    # image: assets/icons/lundri_connect_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/sounds/request_ring.mp3
