// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQO8NrI-cbr0tVS8C0RxgkK2PEKi8VUIo',
    appId: '1:464337931141:android:5df132e4eb6b5683c7d2ec',
    messagingSenderId: '464337931141',
    projectId: 'omeeo-wash',
    storageBucket: 'omeeo-wash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuTFgGzOryt_k-72dAezV9TkoNJmpRyJg',
    appId: '1:464337931141:ios:8c5a858508c20eb1c7d2ec',
    messagingSenderId: '464337931141',
    projectId: 'omeeo-wash',
    storageBucket: 'omeeo-wash.firebasestorage.app',
    androidClientId:
        '464337931141-2rdgeqg9lemgm169cn6clhujiqquiav0.apps.googleusercontent.com',
    iosClientId:
        '464337931141-02ag2d1rsrie3bdmglu6673r8oaeikfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.lundriConnect',
  );
}
